FROM alpine:3.16.3
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN apk add --update --no-cache py3-pip && pip install kafka-python
RUN mkdir /app
COPY producer.py /app
WORKDIR /app
ARG KAFKA_HOST
ENV ENV_KAFKA_HOST=&KAFKA_HOST 
ENTRYPOINT python3 producer.py ${ENV_KAFKA_HOST}