version: '3.1'

services:
  producer:
    container_name: producer
    image: producer
    restart: always
    environment:
      KAFKA_HOST: kafka
    depends_on:
      - kafka

  consumer:
    container_name: consumer
    image: consumer
    restart: always
    environment:
      KAFKA_HOST: kafka
      CLICKHOUSE_HOST: clickhouse
    depends_on:
      - kafka
      - clickhouse

  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:21.3
    restart: always
    volumes:
      - /data/clickhouse:/var/lib/clickhouse
    ports:
      - 8123:8123

  kafka:
    container_name: kafka
    image: ubuntu/kafka:3.1-22.04_edge
    restart: always
    depends_on:
      - clickhouse
      - zookuper
    environment:
      ZOOKEEPER_HOST: zookuper
  
  zookuper:
    container_name: zookuper
    image: zookeeper:3.6.3-temurin
    restart: always