FROM alpine:3.16.3
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN apk add --update --no-cache py3-pip && pip install clickhouse-connect ; pip install kafka-python
RUN mkdir /app
COPY consumer.py /app
WORKDIR /app
ENTRYPOINT ["python3","producer.py"]
CMD ["localhost", "localhost"]